/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uy.cursojava.proyecto.RiegoSYS.Presentación;

import uy.cursojava.proyecto.RiegoSYS.Presentacion.Inicio;
import uy.cursojava.proyecto.RiegoSYS.Logica.Contrato;
import uy.cursojava.proyecto.RiegoSYS.Logica.Empleado;
import uy.cursojava.proyecto.RiegoSYS.Sistema.Sistema;

/**
 *
 * @author rodrigo denis, rodrigo silveria, bruno rasetti
 */
public class RegistroEmpleado extends javax.swing.JFrame {

    /**
     * Creates new form empleadoDatos
     */
    Sistema s = new Sistema();

    public RegistroEmpleado() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        empleadoNombre = new javax.swing.JLabel();
        empleadoApellido = new javax.swing.JLabel();
        empleadoCI = new javax.swing.JLabel();
        empleadoCelular = new javax.swing.JLabel();
        empleadoDireccion = new javax.swing.JLabel();
        empleadoBanco = new javax.swing.JLabel();
        empleadoCuentabanco = new javax.swing.JLabel();
        empleadoNombreTxt = new javax.swing.JTextField();
        empleadoApellidoTxt = new javax.swing.JTextField();
        empleadoCITxt = new javax.swing.JTextField();
        empleadoCelularTxt = new javax.swing.JTextField();
        empleadoDireccionTxt = new javax.swing.JTextField();
        empleadoBancoTxt = new javax.swing.JTextField();
        empleadoCuentabancoTxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jCrearEmpleado = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        empleadoTipoEmpleado = new javax.swing.JTextField();
        empleadoTipoCon = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        empleadoEmail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        empleadoTipoSalario = new javax.swing.JTextField();
        jLabelError = new javax.swing.JLabel();
        jLabelError1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        empleadoNombre.setText("Nombres:");

        empleadoApellido.setText("Apellidos:");

        empleadoCI.setText("C.I:");

        empleadoCelular.setText("Número celular:");

        empleadoDireccion.setText("Dirección:");

        empleadoBanco.setText("Banco:");

        empleadoCuentabanco.setText("Cuenta de banco:");

        jLabel1.setText("Registro de Empleado");

        jCrearEmpleado.setText("Crear");
        jCrearEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCrearEmpleadoActionPerformed(evt);
            }
        });

        jLabel2.setText("Tipo de contrato:");

        jLabel3.setText("Tipo de salario:");

        jLabel4.setText("Email");

        jLabel5.setText("Tipo de empleado");

        jMenu1.setText("Inicio");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(empleadoApellido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(empleadoNombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(empleadoCI)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(empleadoEmail)
                            .addComponent(empleadoNombreTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                            .addComponent(empleadoApellidoTxt)
                            .addComponent(empleadoCITxt, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(empleadoCelular)
                            .addComponent(empleadoDireccion)
                            .addComponent(empleadoBanco)
                            .addComponent(empleadoCuentabanco)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(empleadoTipoCon)
                            .addComponent(empleadoCelularTxt, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(empleadoDireccionTxt, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(empleadoBancoTxt, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(empleadoCuentabancoTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                            .addComponent(empleadoTipoSalario, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelError)
                            .addComponent(empleadoTipoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelError1))))
                .addContainerGap(161, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jCrearEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(206, 206, 206))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(empleadoNombreTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(empleadoNombre))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(empleadoApellidoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(empleadoApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(empleadoCITxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(empleadoCI))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(empleadoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(empleadoCelular)
                    .addComponent(empleadoCelularTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(empleadoDireccion)
                    .addComponent(empleadoDireccionTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(empleadoBanco)
                    .addComponent(empleadoBancoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(empleadoCuentabanco)
                    .addComponent(empleadoCuentabancoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(empleadoTipoCon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(empleadoTipoSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(empleadoTipoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelError)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelError1)
                .addGap(12, 12, 12)
                .addComponent(jCrearEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCrearEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCrearEmpleadoActionPerformed
        Empleado e = new Empleado();
        e.setApellido(empleadoApellidoTxt.getText());
        e.setBanco(empleadoCuentabancoTxt.getText());
        e.setContrato(tipoContrato(empleadoTipoCon.getText(), empleadoTipoSalario.getText()));
        e.setCueBanPago(Integer.valueOf(empleadoCuentabancoTxt.getText()));
        e.setDirecc(empleadoDireccionTxt.getText());
        try {
            e.setDocumento(Integer.valueOf(empleadoCITxt.getText()));
            e.setNumCel(Integer.valueOf(empleadoCelularTxt.getText()));
        } catch (NumberFormatException c) {
            jLabelError.setText("Ingrese bien el su Documento o su Numero de Celular");
        }
        if (tipoEmpleado(empleadoTipoEmpleado.getText()) != 0) {
            e.setTipoEmpleado(tipoEmpleado(empleadoTipoEmpleado.getText()));
            System.out.println("agrego");
        } else {
            jLabelError1.setText("Debe ingresar un tipo de empleado correcto");
        }
        e.setEmail(empleadoEmail.getText());
        e.setNombre(empleadoNombreTxt.getText());
        try {
            s.getListaEmpleado().add(e);
        } catch (NullPointerException j) {
            jLabelError.setText("Debe ingresar todos los datos del Empleado");
        }
    }//GEN-LAST:event_jCrearEmpleadoActionPerformed

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        Inicio in = new Inicio();
        in.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenu1MouseClicked

    private Integer tipoEmpleado(String tipoEmpleado) {
        Integer tipoE = 0;
        if (tipoEmpleado.equalsIgnoreCase("Mensual")) {
            tipoE = 1;
        } else if (tipoEmpleado.equalsIgnoreCase("Jornalero")) {
            tipoE = 2;
        }
        return tipoE;
    }
    
    private Contrato tipoContrato(String tipoS, String tipoC) {
        Contrato c = new Contrato();
        if (tipoS.equalsIgnoreCase("Mensual")) {
            c.setTipoSalario("Mensual");
        } else if (tipoS.equalsIgnoreCase("Quincenal")) {
            c.setTipoSalario("Quincenal");
        }
        if (tipoC.equalsIgnoreCase("Mensual")) {
            c.setTipoContrato("Mensual");
        } else if (tipoC.equalsIgnoreCase("Jornalero")) {
            c.setTipoContrato("Jornalero");
        }
        return c;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel empleadoApellido;
    private javax.swing.JTextField empleadoApellidoTxt;
    private javax.swing.JLabel empleadoBanco;
    private javax.swing.JTextField empleadoBancoTxt;
    private javax.swing.JLabel empleadoCI;
    private javax.swing.JTextField empleadoCITxt;
    private javax.swing.JLabel empleadoCelular;
    private javax.swing.JTextField empleadoCelularTxt;
    private javax.swing.JLabel empleadoCuentabanco;
    private javax.swing.JTextField empleadoCuentabancoTxt;
    private javax.swing.JLabel empleadoDireccion;
    private javax.swing.JTextField empleadoDireccionTxt;
    private javax.swing.JTextField empleadoEmail;
    private javax.swing.JLabel empleadoNombre;
    private javax.swing.JTextField empleadoNombreTxt;
    private javax.swing.JTextField empleadoTipoCon;
    private javax.swing.JTextField empleadoTipoEmpleado;
    private javax.swing.JTextField empleadoTipoSalario;
    private javax.swing.JButton jCrearEmpleado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelError;
    private javax.swing.JLabel jLabelError1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
