/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uy.cursojava.proyecto.RiegoSYS.Presentacion;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import uy.cursojava.proyecto.RiegoSYS.Excepciones.ClienteNoValidoException;
import uy.cursojava.proyecto.RiegoSYS.Excepciones.ServicioNoValidoException;

import uy.cursojava.proyecto.RiegoSYS.Logica.Cliente;
import uy.cursojava.proyecto.RiegoSYS.Logica.Empleado;
import uy.cursojava.proyecto.RiegoSYS.Logica.FachadaServicio;
import uy.cursojava.proyecto.RiegoSYS.Logica.Servicio;
import uy.cursojava.proyecto.RiegoSYS.Presentacion.Inicio;
//import uy.cursojava.proyecto.RiegoSYS.Sistema.Sistema;

/**
 *
 * @author rodrigo, rodrigo silveria, bruno rasetti
 */
public class VentanaServicio extends javax.swing.JFrame {

    /**
     * Creates new form ventanaServicio
     */
    public VentanaServicio() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cedulaEmpleado = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        idProd = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jDocumentoCli = new javax.swing.JTextField();
        jBotonAddServicio = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        datePickerServicio = new com.github.lgooddatepicker.components.DatePicker();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cedulaEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cedulaEmpleadoActionPerformed(evt);
            }
        });

        jLabel1.setText("Empleado:");

        idProd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bomba Electrica", "Bomba Hidraulica", "Bomba Comun", "Bomba Mecanica" }));

        jLabel2.setText("Producto:");

        jLabel3.setText("Cliente:");

        jLabel4.setText("Fecha realización:");

        jBotonAddServicio.setText("Agregar");
        jBotonAddServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonAddServicioActionPerformed(evt);
            }
        });

        jLabel5.setText("Registro De Servicio");

        jMenu1.setText("Inicio");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(97, 97, 97)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cedulaEmpleado)
                            .addComponent(idProd, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jDocumentoCli)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(datePickerServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(72, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jBotonAddServicio)
                .addGap(44, 44, 44))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cedulaEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(idProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jDocumentoCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(datePickerServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(jBotonAddServicio)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 
    private FachadaServicio fachada = new FachadaServicio();
    
    private void crearServicio() throws ServicioNoValidoException {
      
      Servicio servicio= new Servicio();
      Empleado empleado = new Empleado();
      Cliente cliente = new Cliente();
        
        try { 
        empleado.setDocumento(Integer.valueOf(cedulaEmpleado.getText()));
        cliente.setDocumento(Integer.valueOf(jDocumentoCli.getText()));
        servicio.setEmpleado(empleado);
        servicio.setCliente(cliente);
        servicio.setTipoServicio(obtenerTipoServicio());
       // servicio.setFecha(datePickerServicio.getText());
        servicio.setFecha(datePickerServicio.getDate());
        fachada.agregarServicio(servicio);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Debe ingresar una C.I valida: ");
       }
      }
        //try {
//            
                //this.fachada.agregarServicio(servicio);
                //JOptionPane.showMessageDialog(this, "Se creó el servicio: " );
                //limpiarCampos();
//            }
       // } catch (ServicioNoValidoException ex) {
          //  Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
           // JOptionPane.showMessageDialog(this, ex.getMessage());
    //}
        
        
        //}
    
   // private void limpiarCampos() {
          // cedulaEmpleado.setText(null);
           //jDocumentoCli.setText(null);
           //datePickerServicio.setText(null);
          // }
      
  
    private void cedulaEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cedulaEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cedulaEmpleadoActionPerformed

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        Inicio in = new Inicio();
        in.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenu1MouseClicked
 
    
    private void jBotonAddServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonAddServicioActionPerformed
        try {
            crearServicio();
        } catch (ServicioNoValidoException ex) {
            Logger.getLogger(VentanaServicio.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBotonAddServicioActionPerformed

      
private String obtenerTipoServicio() {
        return idProd.getItemAt(idProd.getSelectedIndex());

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cedulaEmpleado;
    private com.github.lgooddatepicker.components.DatePicker datePickerServicio;
    private javax.swing.JComboBox<String> idProd;
    private javax.swing.JButton jBotonAddServicio;
    private javax.swing.JTextField jDocumentoCli;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
