/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uy.cursojava.proyecto.RiegoSYS.Presentacion;

import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.ListModel;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import uy.cursojava.proyecto.RiegoSYS.Excepciones.BDException;
import uy.cursojava.proyecto.RiegoSYS.Excepciones.EmpleadoNoValidoException;
import uy.cursojava.proyecto.RiegoSYS.Logica.Empleado;
import uy.cursojava.proyecto.RiegoSYS.Logica.FachadaContrato;
import uy.cursojava.proyecto.RiegoSYS.Logica.FachadaEmpleado;

/**
 *
 * @author rodrigo denis, rodrigo silveria, bruno rasetti
 */
public class VentanaBusquedaEmpleado extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame1
     */
    public VentanaBusquedaEmpleado() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldNombreEmpleado = new javax.swing.JTextField();
        buscar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        botonEliminarEmpleado = new javax.swing.JButton();
        botonEditarEmpleado = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableEmpleado = new javax.swing.JTable();
        jButtonActualizar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buscar.setText("Buscar");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });

        jLabel2.setText("Buesqueda empleado");

        jLabel3.setText("Nombre del empleado");

        botonEliminarEmpleado.setText("Eliminar");
        botonEliminarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarEmpleadoActionPerformed(evt);
            }
        });

        botonEditarEmpleado.setText("Editar");
        botonEditarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEditarEmpleadoActionPerformed(evt);
            }
        });

        jTableEmpleado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Apellido", "Documento", "Direccion", "Email", "Celular", "Cuenta Banco", "Banco"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTableEmpleado);

        jButtonActualizar.setText("Actualizar");
        jButtonActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActualizarActionPerformed(evt);
            }
        });

        jMenu1.setText("Inicio");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(botonEliminarEmpleado)
                .addGap(18, 18, 18)
                .addComponent(jButtonActualizar)
                .addGap(18, 18, 18)
                .addComponent(botonEditarEmpleado)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldNombreEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(buscar)
                .addGap(0, 205, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNombreEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscar)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonEliminarEmpleado)
                    .addComponent(botonEditarEmpleado)
                    .addComponent(jButtonActualizar))
                .addGap(58, 58, 58))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private FachadaEmpleado fachada = new FachadaEmpleado();
    private FachadaContrato fachadaContrato = new FachadaContrato();
    private String nombreAux = " ";

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        Inicio in = new Inicio();
        in.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenu1MouseClicked

    private void listar(String nombreEmpleado) {
        Empleado e = new Empleado();
        e.setNombre(nombreEmpleado);
        try {
            ArrayList<Empleado> listaEmp = fachada.fachaEmpleadoListar(e);
            DefaultTableModel tablaEmpleadoModel = (DefaultTableModel) jTableEmpleado.getModel();
            jTableEmpleado.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
            tablaEmpleadoModel.setRowCount(0);
            Empleado empleado = null;
            for (int i = 0; i < listaEmp.size(); i++) {
                empleado = listaEmp.get(i);
                String nombre = empleado.getNombre();
                String apellido = empleado.getApellido();
                Integer documento = empleado.getDocumento();
                String direcc = empleado.getDirecc();
                String email = empleado.getEmail();
                Integer cel = empleado.getNumCel();
                Integer cuentaBanco = empleado.getCueBanPago();
                String banco = empleado.getBanco();
                Object[] data = {nombre, apellido, documento, direcc, email, cel, cuentaBanco, banco};
                tablaEmpleadoModel.addRow(data);
            }
            jTextFieldNombreEmpleado.setText("");
        } catch (EmpleadoNoValidoException ex) {
            Logger.getLogger(VentanaBusquedaEmpleado.class.getName()).log(Level.SEVERE, null, ex);
        }
    }


    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        nombreAux = jTextFieldNombreEmpleado.getText();
        listar(jTextFieldNombreEmpleado.getText());
    }//GEN-LAST:event_buscarActionPerformed

    private void botonEliminarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarEmpleadoActionPerformed
        Empleado e = new Empleado();
        Integer row = jTableEmpleado.getSelectedRow();
        Integer column = 2; //columna donde se encuentra el documento del empleado a eliminar
        Integer documento = (Integer) jTableEmpleado.getModel().getValueAt(row, column);
        e.setDocumento(documento);
        nombreAux = (String) jTableEmpleado.getModel().getValueAt(row, 0);
        try {
            fachadaContrato.fachaContratoEliminar(e.getDocumento());
            fachada.fachaEmoleadoEliminar(e);
            JOptionPane.showMessageDialog(this, "Se eliminó el empleado: " + (String) jTableEmpleado.getModel().getValueAt(row, 0) + " de numero de documento: " + e.getDocumento());
        } catch (EmpleadoNoValidoException ex) {
            Logger.getLogger(VentanaBusquedaEmpleado.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botonEliminarEmpleadoActionPerformed

    private void botonEditarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEditarEmpleadoActionPerformed
        Empleado e = new Empleado();
        Integer row = jTableEmpleado.getSelectedRow();
        Integer column = jTableEmpleado.getSelectedColumn();
        String NombreColumna = jTableEmpleado.getColumnName(column);
        String contenido = (String) jTableEmpleado.getModel().getValueAt(row, column);
        switch (NombreColumna) {
            case "Direccion"://row 3
                e.setDirecc(contenido);
                e.setEmail((String) jTableEmpleado.getModel().getValueAt(row, 4));
                e.setNumCel((Integer) jTableEmpleado.getModel().getValueAt(row, 5));
                e.setCueBanPago((Integer) jTableEmpleado.getModel().getValueAt(row, 6));
                e.setBanco((String) jTableEmpleado.getModel().getValueAt(row, 7));
                break;
            case "Email"://row 4
                e.setEmail(contenido);
                e.setNumCel((Integer) jTableEmpleado.getModel().getValueAt(row, 5));
                e.setCueBanPago((Integer) jTableEmpleado.getModel().getValueAt(row, 6));
                e.setBanco((String) jTableEmpleado.getModel().getValueAt(row, 7));
                e.setDirecc((String) jTableEmpleado.getModel().getValueAt(row, 3));
                break;
            case "Celular"://row 5
                e.setNumCel(Integer.valueOf(contenido));
                e.setCueBanPago((Integer) jTableEmpleado.getModel().getValueAt(row, 6));
                e.setBanco((String) jTableEmpleado.getModel().getValueAt(row, 7));
                e.setDirecc((String) jTableEmpleado.getModel().getValueAt(row, 3));
                e.setEmail((String) jTableEmpleado.getModel().getValueAt(row, 4));
                break;
            case "Cuenta Banco": //row 6
                e.setCueBanPago(Integer.valueOf(contenido));
                e.setDirecc((String) jTableEmpleado.getModel().getValueAt(row, 3));
                e.setEmail((String) jTableEmpleado.getModel().getValueAt(row, 4));
                e.setNumCel((Integer) jTableEmpleado.getModel().getValueAt(row, 5));
                e.setBanco((String) jTableEmpleado.getModel().getValueAt(row, 7));
                break;
            case "Banco"://row 7
                e.setBanco(contenido);
                e.setDirecc((String) jTableEmpleado.getModel().getValueAt(row, 3));
                e.setEmail((String) jTableEmpleado.getModel().getValueAt(row, 4));
                e.setNumCel((Integer) jTableEmpleado.getModel().getValueAt(row, 5));
                e.setCueBanPago((Integer) jTableEmpleado.getModel().getValueAt(row, 6));
                break;
        }
        Integer columnDoc = 2; //columna donde se encuentra el documento del empleado a eliminar
        Integer documento = (Integer) jTableEmpleado.getModel().getValueAt(row, columnDoc);
        e.setDocumento(documento);
        fachada.fachaEmpleadoModificar(e);
    }//GEN-LAST:event_botonEditarEmpleadoActionPerformed

    private void jButtonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActualizarActionPerformed
        listar(nombreAux);
    }//GEN-LAST:event_jButtonActualizarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonEditarEmpleado;
    private javax.swing.JButton botonEliminarEmpleado;
    private javax.swing.JButton buscar;
    private javax.swing.JButton jButtonActualizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTableEmpleado;
    private javax.swing.JTextField jTextFieldNombreEmpleado;
    // End of variables declaration//GEN-END:variables
}
